# Generated by Django 3.2.9 on 2022-01-10 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientindexpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='clientpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='clientpage',
            name='date',
        ),
        migrations.AddField(
            model_name='clientpage',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='clientpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
